### ISSUE TITLE
can't find JANET_FILE_PIPED in module evil_janet

### ISSUE THREAD

**Issue by glyh** [GrayJack/janetrs#5]
I'm trying to create a demo:
```rust
use janetrs::client::{Error, JanetClient};

fn main() -> Result<(), Error> {
    let client = JanetClient::init_with_default_env()?;

    client.run("(print `Hello from Janet!`)")?;

    let out = client.run("(+ 2 2)")?;

    println!("{}", out);

    Ok(())
}
```
I don't modify the feature flags of janet.
When I try to compile, I run into this:
```
   Compiling janetrs v0.5.0
error[E0425]: cannot find value `JANET_FILE_PIPED` in crate `evil_janet`
   --> /home/lyh/.cargo/registry/src/github.com-1ecc6299db9ec823/janetrs-0.5.0/src/types/io.rs:319:46
    |
319 |     pub const PIPED: Self = Self(evil_janet::JANET_FILE_PIPED as i32);
    |                                              ^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `JANET_FILE_APPEND`
    |
   ::: /home/lyh/Test/hello_jrs/target/debug/build/evil-janet-3c3a63e12ae3fb5f/out/bindings.rs:94:1
    |
94  | pub const JANET_FILE_APPEND: u32 = 4;
    | -------------------------------- similarly named constant `JANET_FILE_APPEND` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `janetrs` due to previous error
```
How can I fix this? Thank you!

**Comment by yrns** [comment]
Looks like it was removed in https://github.com/janet-lang/janet/commit/fe7d35171f0f74338ecbadf4aa5e0dbf76b4becf, in version 1.22.0. The version of evil-janet should probably be more specific than "1". @glyh Use a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) to get the latest version from here.

**Comment by DianaOlympos** [comment]
This was fixed in https://github.com/GrayJack/janetrs/commit/78921908a9f6d1817f6a5aa797180e42560e1993

@GrayJack Do you think we could have a versioned release of the crates that comprise this? I can totally keep it as a git dependency for now, but I think that for newcomers to using Janet from Rust, having a version on crates.io that works is probably nicer :heart:

**Comment by GrayJack** [comment]
Sorry, people for the lack of response. My GH notifications became flooded with work-related notifications and I end up missing issues and comments in my open-source projects.

I agree, a new release is needed, I just want to adjust a few things and fix other open issues during this weekend.

**Comment by GrayJack** [comment]
Hey there people! I finally solved everything I wanted for the next release! And now it is online!

Here is the [discussion topic](https://github.com/GrayJack/janetrs/discussions/8)
